// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PickEm.Models;

namespace PickEm.Web.Migrations
{
    [DbContext(typeof(PickEmContext))]
    [Migration("20190603204048_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("PickEm.Models.BracketModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CorrectPicks");

                    b.HasKey("Id");

                    b.ToTable("BracketModel");
                });

            modelBuilder.Entity("PickEm.Models.GameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AwayScore");

                    b.Property<int?>("AwayTeamId");

                    b.Property<int?>("BracketId");

                    b.Property<int?>("HomeScore");

                    b.Property<int?>("HomeTeamId");

                    b.Property<bool?>("Prediction");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("BracketId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("GameModel");
                });

            modelBuilder.Entity("PickEm.Models.TeamModel", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("AvgAst");

                    b.Property<decimal?>("AvgBlk");

                    b.Property<decimal?>("AvgDefReb");

                    b.Property<decimal?>("AvgOffReb");

                    b.Property<decimal?>("AvgOppScore");

                    b.Property<decimal?>("AvgScore");

                    b.Property<decimal?>("AvgStl");

                    b.Property<string>("Name");

                    b.Property<int>("Seed");

                    b.HasKey("TeamId");

                    b.ToTable("TeamModel");
                });

            modelBuilder.Entity("PickEm.Models.GameModel", b =>
                {
                    b.HasOne("PickEm.Models.TeamModel", "AwayTeam")
                        .WithMany("AwayGames")
                        .HasForeignKey("AwayTeamId");

                    b.HasOne("PickEm.Models.BracketModel", "Bracket")
                        .WithMany("Games")
                        .HasForeignKey("BracketId");

                    b.HasOne("PickEm.Models.TeamModel", "HomeTeam")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
