// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PickEm.Models;

namespace PickEm.Web.Migrations
{
    [DbContext(typeof(PickEmContext))]
    partial class PickEmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("PickEm.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AwayScore");

                    b.Property<int>("AwayTeamId");

                    b.Property<int>("HomeScore");

                    b.Property<int>("HomeTeamId");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("PickEm.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AvgBlk");

                    b.Property<decimal>("AvgDefReb");

                    b.Property<decimal>("AvgOffReb");

                    b.Property<decimal>("AvgOppScore");

                    b.Property<decimal>("AvgScore");

                    b.Property<decimal>("AvgStl");

                    b.Property<string>("Name");

                    b.Property<int>("Seed");

                    b.Property<int>("TeamId");

                    b.HasKey("Id");

                    b.ToTable("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
